# Generated by Django 4.1.2 on 2022-10-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=37)),
                ('price', models.CharField(max_length=10)),
                ('barber_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('categori', models.BigIntegerField()),
            ],
        ),
    ]
