# Generated by Django 4.1.2 on 2022-11-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hairdresser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('phone', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=100)),
            ],
        ),
    ]
