# Generated by Django 4.1.2 on 2022-11-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_hairdresser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairdresser',
            name='occupation',
            field=models.CharField(max_length=50),
        ),
    ]
