# Generated by Django 4.1.2 on 2022-11-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_hairdresser_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked_appointmentss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.user')),
            ],
        ),
    ]
