# Generated by Django 4.1.2 on 2022-12-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_booked_appointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked_appointments1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
