# Generated by Django 4.1.5 on 2023-01-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_booked_appointmentss'),
        ('Home', '0006_booked_appointments1'),
    ]

    operations = [
    ]
