# Generated by Django 4.1.5 on 2023-01-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_booked_appointments1'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='time',
            field=models.TimeField(default='0:00'),
            preserve_default=False,
        ),
    ]
