# Generated by Django 4.1.5 on 2023-02-09 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_price_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked_appointments1',
            name='categori',
            field=models.ForeignKey(db_column='categori', default=True, on_delete=django.db.models.deletion.CASCADE, to='Home.price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booked_appointments1',
            name='hairdresser_id',
            field=models.BigIntegerField(default=True),
            preserve_default=False,
        ),
    ]
